package by.tc.finalproject.controller.command;

public enum CommandTitle {
	LOGINATION, REGISTRATION, LOGOUT,GOTOINDEXPAGE,
	GOTOADMINPAGE,GOTOPERSONPAGE,GOTOREGISTERPAGE,GOTOLOGINPAGE,
	GOTOEDITPAGE,EDITING,DELETEACCOUNT,GOTOLISTOFAPPLICANTS
}
