package by.tc.applicant.controller.command;

public enum CommandTitle {
	LOGINATION, REGISTRATION, GOTOADMINPAGE, GOTOPERSONPAGE, GOTOREGISTERPAGE, GOTOLOGINPAGE, GOTOEDITPAGE, EDITING,
	DELETEACCOUNT, GOTOLISTOFAPPLICANTS, DELETEACCOUNTFROMADMIN, EDITUSERFROMADMIN, GOTOEDITUSERFROMADMIN,
	CREATELISTOFENROLLED, CHECKADMISSIONRESULT, GOTOMAINPAGE, GOTOABOUTPAGE, GOTOFACULTYPAGE, GOTOCONTACTPAGE,
	GOTONEWSPAGE, GOTOEFPAGE, GOTOFKSISPAGE, GOTOINFOPAGE, GOTOFITUPAGE, GOTOFKPPAGE, GOTOFRPAGE, EXIT
}
